### ISSUE TITLE
Can't open module file 'type.mod'

### ISSUE THREAD

**Issue by pierreo78** [LHEEA/HOS-ocean#10]
Bonjour, 

je pense avoir respecté les étapes d'installation mais quand je compile j'obtiens l'erreur " Fatal Error : Can't open module file 'type.mod' for reading at (1) " 
l'erreur se produit lorsqu'il veut compiler runge_kutta.o 

j'ai vérifié, les libs et les installations de fftw et lapack sont bonnes, 

auriez vous une idée du problème ? 

Merci d'avance

**Comment by pierreo78** [comment]
Le problème a disparu en redémarrant la machine virtuelle, néanmoins quand je veux lancer le programme compiler j'obtiens Fortran runtime error 'Results/restart_data.dat' does not exist, je suppose que ce fichier est crée pendant l'execution du programme et donc il doit toujours y avoir un problème lors de la compilation

**Comment by gducrozet** [comment]
@pierreo78 
Avant l'exécution du programme, il ne faut pas oublier de créer un dossier Results à l'endroit de l'exécution. Il me semble qu'en cas d'oubli, cette erreur apparaît.

Guillaume.

**Comment by pierreo78** [comment]
Le dossier existe bel et bien, j'ai l'impression ( je me trompe peut-être ) , que ce fichier "restart_data.dat" est le fichier des données déjà calculées dans le cas où on veut reprendre un calcul déjà commencé, 
or la variable i_restart est bien à 0 dans mon input_HOS.dat , 

le programme ne devrait pas essayer d'ouvrir ce fichier dans ce cas non ?

**Comment by pierreo78** [comment]
A priori c'est bon tout fonctionne, c'était un problème de droit d'écriture, merci pour votre aide
