### ISSUE TITLE
reconstruction of surface elevation from modes

### ISSUE THREAD

**Issue by waynezw0618** [LHEEA/HOS-ocean#21]
Hi 
I am wondering how we can use results from modes to reconstruct surface elevation. 
I found two data file, **3d.dat** ,**a_3d.dat,** two files. for the former one get eta and phis while the latter according to file it gives wave number k, a, ..., blabla..., my understand is that I can use sum over nk  a_i*sin(k_i) to reconstruct eta for each time. but seems it gives totally two different results. or do I miss something， like normallization ？while I noticed there is file **modes_HOS_SWENSE.dat**， do I need to use this data？

**Comment by YoungmChoi** [comment]
Dear Wei Zhang,

Yes. You can use LHEEA/Grid2Grid (execution: postGrid2Grid) with modes_HOS_SWENSE.dat to regenerate the surface elevation.

Please try it and let me know if you have a problem.

Best regards,
Young-Myung CHOI

**Comment by YoungmChoi** [comment]
Dear Wei Zhang,

You can do it manually. There are subroutines in Grid2Grid "src/libGrid2Grid/surf2Vol/HOSOcean/hosOcean/inc"

- init_read_mod: Read HOS parameters (nX, nY, ...)
- read_ascii_mod_HOSOcean: Read HOS modal amplitudes at each HOS time

Because you already know the modal amplitudes at each time, you can reconstruct them by formula.
Or you can refer the subroutine "reconstruction_direct" in HOS-ocean "sources/PostProcessing/reconstruction.f90".

Have a nice day,

Best regards,
Youngmyung CHOI

**Comment by gducrozet** [comment]
Dear Wei Zhang,

Complementary to the reply of Youngmyung (thanks for being reactive on this!) this is not possible to reconstruct directly from the file a_3d.dat the free surface elevation / free surface velocity potential.
The point is that a_3d.dat stores only the wavenumbers and modulus of complex modal amplitudes. Then, the phase of each component is the missing information for what you want to achieve.

Best,
Guillaume

**Comment by waynezw0618** [comment]
Hi @gducrozet & @YoungmChoi 
 thanks all for reply.
I tried postG2G in grid2grid. still I cannot get perfect solution.see below
![WechatIMG1636](https://user-images.githubusercontent.com/10613022/155993525-52f7b060-1ef3-46c1-9ca0-bc1c48cdf0f4.png)
 and there are some parameters which I don't know how to set.
![WechatIMG1622](https://user-images.githubusercontent.com/10613022/155993617-7aa10917-bf74-4ba7-92c9-7d0e97137ae8.png)

BTW regarding to @gducrozet. I suppose phase is not the only thing we miss here. because there is bspline library over there. is there any theory document to gives some detailed information?

Best 
Wei
