### ISSUE TITLE
Dirichlet-Neumann Operatior kappa 

### ISSUE THREAD

**Issue by waynezw0618** [LHEEA/HOS-ocean#22]
Hello 
can anyone tell me how to solve phi_z in both equations.do you really need to solve the boundary value problem described by the Laplacian equation. or any tips like in Pan's paper, use DNO, kappa, to calculate that? but how to calculate kappa

[1]On high-order perturbation expansion for the study of long–short wave interactions J. Fluid Mech. (2018), vol. 846, pp. 902–915.

Thanks

Wei

**Comment by waynezw0618** [comment]
Hello Again
my question is how to calculate the DNO from some explicit formula, where is the implementation in the HOS code

**Comment by gducrozet** [comment]
HOS and DNO are indeed equivalent, as demonstrated in: https://doi.org/10.1016/j.coastaleng.2007.11.002

Then, you can refer to HOS algorithm, which is more accessible to understand how the BVP is solved.
