### ISSUE TITLE
Error Encountered in i_case=33

### ISSUE THREAD

**Issue by adefaizal** [LHEEA/HOS-ocean#29]
Hello

I am trying to run the HOS model with i_case=33 (initialization with a spectrum file containing the description of the directional spectrum). I have the spectrum file: SPEC_20181006-01_SKOREA.2D, but when I run the model, I encounter the following error:

![image](https://github.com/user-attachments/assets/5ff770e5-281c-4758-9ac3-40fbc728f73b)

Has anyone experienced a similar problem or knows how to fix it?

Thank you

Best regards,
Faizal

**Comment by gducrozet** [comment]
Hello @adefaizal 

This version of the code is not maintained anymore. I strongly advise you to use the up-to-date version of code available [on Gitlab](https://gitlab.com/lheea/HOS-Ocean) and ask for possible feedback there

Guillaume.

**Comment by adefaizal** [comment]
Hello Guillaume,

Thank you for the information. I’ll reach out on GitLab for any further feedback.

Best regards,
Faizal
