### ISSUE TITLE
Unidirectional results change with n2

### ISSUE THREAD

**Issue by dh810** [LHEEA/HOS-ocean#7]
When running unidirectional JONSWAP waves (beta = 0.0, case = 3), the result appears to be different when using n2=1 and n2>1. I would expect the value of n2 to make no difference to the result when beta=0.0.
In order to see the difference, change variables `angle1`, `angle2 `and `angle` to `0.0_rp`. This would remove any randomness from the simulation and create a focused wave.

This issue is resolved if line 514 in initial_condition.f90 is changed from 
`IF(n2 == 1) THEN`
to
`IF ((n2 == 1) .OR.(ABS(beta).LE.tiny)) THEN`

Implementing the above change means that the division by `k_abs` is ignored when beta=0.0. I am not sure if this is change is correct, because dividing by `k_abs` is the correct operation to transform the spectrum:
[<a href="https://www.codecogs.com/eqnedit.php?latex=E(k_x,k_y)&space;=&space;E(\omega,\theta)&space;\frac{c_g}{|k|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?E(k_x,k_y)&space;=&space;E(\omega,\theta)&space;\frac{c_g}{|k|}" title="E(k_x,k_y) = E(\omega,\theta) \frac{c_g}{|k|}" /></a>](url)

**Comment by gducrozet** [comment]
After a bit of thinking about this issue, I think that in the current version of the code, the treatment of the case of unidirectional irregular waves treated in 3D (`beta=0.0` and `n2 =/ 1`) is indeed not perfectly consistant.

As you suggest, this case should probably be treated like a unidirectional case (i.e. similar to the case `n2=1`). The modification you suggest should be sufficient to allow such kind of treatment.

Regarding the implication of such change in a theoretical framework, the current inconsistency comes from the definition of the directional spreading function ![image](https://user-images.githubusercontent.com/9819574/32188351-d7911f42-bda7-11e7-9ffd-4f15818853ea.png)

![image](https://user-images.githubusercontent.com/9819574/32188365-df1d279c-bda7-11e7-84c9-94fa52f49a43.png)

This should satisfy some properties, including ![image](https://user-images.githubusercontent.com/9819574/32188398-fab8d654-bda7-11e7-8591-3e4d8b1be0ae.png)
This is actually not the case with the current definition of directional spreading with `beta=0.0`. Going back to a unidirectional spectrum definition in this configuration looks correct to me as a first thought.
