### ISSUE TITLE
Reason for omega_n2 being defined on extended x-grid and used on x-grid for irregular initialization

### ISSUE THREAD

**Issue by rickyspaceguy** [LHEEA/HOS-ocean#8]
In `variables_3d.f90`
```

    REAL(RP), DIMENSION(md1o2p1,n2)  :: omega_n2,goomega_n2
    REAL(RP), DIMENSION(n2)          :: ky_n2
```

In `HOS_ocean.f90`

 ```
   goomega(1,1)    = 1.0_rp
    !
    DO i2 = 1, n2
        DO i1 = 1, Nd1o2p1
            k2                 = kx(i1) * kx(i1) + ky_n2(i2) * ky_n2(i2)
            omega_n2(i1,i2)    = SQRT(g_star * SQRT(k2) * TANH(SQRT(k2)*depth_star))
            IF (ABS(k2) > tiny) THEN
                goomega_n2(i1,i2)  = g_star / omega_n2(i1,i2)
            ELSE
                goomega_n2(i1,i2) = 1.0_rp
            ENDIF
        ENDDO
    ENDDO
    !
    goomega_n2(1,1) = 1.0_rp
```

Subsequently in `initiate_irreg` and `initiate_irreg_f` in `initial_condition.f90` the initialization of `eta` and `phis` uses `omega_n2` as
```
DO i1 = 2, n1o2p1
....
                   DO i1 = 2, n1o2p1
                  ...
                   END DO
....
END DO
```

For initializing `phi_JONSWAP(n1o2p1,n2)`,  `i1 = 2, nd1o2p1` is not done.  But what if one defines `phi_JONSWAP(nd1o2p1,n2)` and then using `reduce_C` initializes `a_eta` and `a_phis`. This seems more consistent. Is there any technical reason or merely a matter of choice?

**Comment by gducrozet** [comment]
The initialization of `a_eta` and `a_phis` needs to be done only on the original number of modes `(n1o2p1,n2)` which are the modes free of aliasing errors in the computation.

As a consequence, it is not necessary to define `phi_JONSWAP` on the extended modes `(Nd1o2p1,Nd2)`. The `reduce_C` function indeed only truncate the extended modes to the original ones and the result will be identical with the procedure you propose.

The definition of `omega_n2,goomega_n2` on a number of points `(Nd1o2p1,n2)` may be confusing but was actually only here for tests purposes. I think that now only the part `(n1o2p1,n2)` of the matrices are used. The definition of those variables in `variables_3d.f90` may be adjusted to this size (to be checked) to remove unnecessary informations.

Hope this is clearer.
Regards,

Guillaume.
